### ISSUE TITLE
Ukol4 - nevím, jak dál, nechápu zadání

### ISSUE THREAD

**Issue by LudmilaWallovaPrusova** [LudmilaWallovaPrusova/uloziste2#5]
https://github.com/LudmilaWallovaPrusova/uloziste2/commit/54113f02d2c918537e062c48ac0b856cf6991820

**Comment by LudmilaWallovaPrusova** [comment]
https://github.com/LudmilaWallovaPrusova/uloziste2/commit/54113f02d2c918537e062c48ac0b856cf6991820

**Comment by AnetaPopelova** [comment]
U `zmen_narocnost` je naprosto dostacujici `self.narocnost = nova_hodnota `.

Tady u toho pises, ze ti to nedava smysl...
 ```
def pridej_recept (self, recept):
        self.recepty.append(recept)
```

Pri volani teto metody se hodnota jejich parametru (u tebe treba "rohlicky") prida do jiz existujiciho seznamu `recepty`. 
Vznikne tak ["rohlicky"]. A pak ["rohlicky", "ryze"]. 
Stejne by jsi mohla do toho seznamu vkladat recepty z prvni casti cviceni.
