### ISSUE TITLE
2 řešení Ukolu 6 v jednom souboru

### ISSUE THREAD

**Issue by LudmilaWallovaPrusova** [LudmilaWallovaPrusova/uloziste2#8]
https://github.com/LudmilaWallovaPrusova/uloziste2/blob/main/Ukol6.py

**Comment by AnetaPopelova** [comment]
To druhe reseni rozhodne je elegantnejsi 👍 

Mohla bys usetrit jeste jednu podminku a preskocit prvni radek takto:
`for radek in radky[1:]:`

Tip: 

Jde to vyresit treba i takto:
```
replacements = {"1": "A", "2": "B", "3": "C", "4": "D", "5": "F"}
output = [i.translate(str.maketrans(replacements)) for i in content]
```
